version: '3'
services:
  proxy:
    build: .
    image: xesco/dnsproxy
    container_name: dnsproxy_bundle
    networks:
      static_net:
        ipv4_address: 172.30.0.2
    environment:
      # force python to flush to stdout
      - PYTHONUNBUFFERED=1
      #- TLS_HOST=
      #- TLS_PORT=
      #- SPKI=
  unbound:
    image: mvance/unbound:latest
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    ports: 
      - "53:53/udp"
    networks:
      static_net:
        ipv4_address: 172.30.0.3
    container_name: unbound_bundle

networks:
  static_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
