version: '3'
services:
  proxy:
    image: xesco/dnsproxy:latest
    container_name: dnsp_proxy
    networks:
      static_net:
        ipv4_address: 172.30.0.2
    environment:
      # force python to flush to stdout
      - PYTHONUNBUFFERED=1
      # If you change the local port, update unbound service 'ports' and unbound.conf
      #- DNSP_LOCAL_PORT=53
      #- DNSP_LOCAL_HOST=
      #- DNSP_TLS_HOST=8.8.8.8
      #- DNSP_TLS_PORT=853
      #- DNSP_TLS_HOSTNAME=dns.google
      #- DNSP_TLS_SPKI=9OF09YE9udyWAIcbAPu8La8JghFNMarsq1wFuXg1iQA=
  unbound:
    image: mvance/unbound:latest
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    ports: 
      - "53:53/udp"
    networks:
      static_net:
        ipv4_address: 172.30.0.3
    container_name: dnsp_unbound

networks:
  static_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
