version: '3'
services:
  proxy:
    build: .
    image: dnsproxy
    container_name: dnsproxy_bundle
    networks:
      static_net:
        ipv4_address: 172.30.0.2
    environment:
      # force python to flush to stdout
      - PYTHONUNBUFFERED=1
      # config different DNS server (for example Google's public DNS)
      #- TLS_HOST=8.8.8.8
      #- TLS_PORT=853
      #- TLS_HOSTNAME=dns.google
      #- SPKI=CMNCN/AHEjKF27em8W59P9f4vBarFbB5VFPvV6UfQbQ=
  unbound:
    image: mvance/unbound:latest
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    ports: 
      - "53:53/udp"
    networks:
      static_net:
        ipv4_address: 172.30.0.3
    container_name: unbound_bundle

networks:
  static_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
